export const SUBSCRIBE = 'SUBSCRIBE';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';

export const SEARCH_QUERY_CHANGE = 'SEARCH_QUERY_CHANGE';
export const CLEAR_SEARCH_STRING = 'CLEAR_SEARCH_STRING';

export const REGISTER_ACTION = 'REGISTER_ACTION';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';