export const INIT = 'INIT';
export const SUBSCRIBE = 'SUBSCRIBE';

export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const LOGIN_ACTION_ERROR = 'LOGIN_ACTION_ERROR';

export const LOGOUT_ACTION = 'LOGOUT_ACTION';

export const REGISTER_ACTION = 'REGISTER_ACTION';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';