const SET_MEDIA_REQUEST_DATE = 'SET_MEDIA_REQUEST_DATE';
const SET_MEDIA_REQUEST_VIEW = 'SET_MEDIA_REQUEST_VIEW';
const SET_MEDIA_REQUEST_LIKE = 'SET_MEDIA_REQUEST_LIKE';

export { SET_MEDIA_REQUEST_DATE, SET_MEDIA_REQUEST_VIEW, SET_MEDIA_REQUEST_LIKE };