export const SET_MEDIA_REQUEST_DATE = 'SET_MEDIA_REQUEST_DATE';
export const SET_MEDIA_REQUEST_VIEW = 'SET_MEDIA_REQUEST_VIEW';
export const SET_MEDIA_REQUEST_LIKE = 'SET_MEDIA_REQUEST_LIKE';
export const SET_MEDIA_LIKE_INCREMENT = 'SET_MEDIA_LIKE_INCREMENT';
export const SET_MEDIA_LIKE_DECREMENT = 'SET_MEDIA_LIKE_DECREMENT';

export const GET_NEW_MEDIA = 'GET_NEW_MEDIA';

export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FILE_TO_SERVER = 'UPLOAD_FILE_TO_SERVER';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST';
export const ADD_COMMENT_TO_POST_SUCCESS = 'ADD_COMMENT_TO_POST_SUCCESS';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
