const SET_MEDIA_REQUEST_DATE = 'SET_MEDIA_REQUEST_DATE';
const SET_MEDIA_REQUEST_VIEW = 'SET_MEDIA_REQUEST_VIEW';
const SET_MEDIA_REQUEST_LIKE = 'SET_MEDIA_REQUEST_LIKE';

export const GET_NEW_MEDIA = 'GET_NEW_MEDIA';

export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FILE_TO_SERVER = 'UPLOAD_FILE_TO_SERVER';

export { SET_MEDIA_REQUEST_DATE, SET_MEDIA_REQUEST_VIEW, SET_MEDIA_REQUEST_LIKE };