export const SET_PROFILE_REQUEST_DATE = 'SET_PROFILE_REQUEST_DATE';
export const SET_PROFILE_REQUEST_VIEW = 'SET_PROFILE_REQUEST_VIEW';

export const UPLOAD_NEW_PHOTO = 'UPLOAD_NEW_PHOTO';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_ERROR = 'UPLOAD_PHOTO_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
