version: '3'

services:
  php-fpm:
    container_name: web
    build:
      context: php-fpm
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - ./../:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    networks:
      - internal

  nginx:
    container_name: nginx
    image: nginx:1.17.2
    ports:
      - 8080:80
    volumes:
      - ./../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - internal

  db:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: geekgram
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28