export const SEARCH_QUERY_CHANGE = 'SEARCH_QUERY_CHANGE';
export const CLEAR_SEARCH_STRING = 'CLEAR_SEARCH_STRING';

export const GET_SEARCHED_DATA = 'GET_SEARCHED_DATA';
export const SEARCH_RESPONSE_SUCCESS = 'SEARCH_RESPONSE_SUCCESS';
export const SEARCH_RESPONSE_ERROR = 'SEARCH_RESPONSE_ERROR'